pipeline:

  test:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request, tag]

  build:
    image: docker:17.09.1
    secrets:
      - npm_auth_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl-schema .
    when:
      event: tag

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-schema quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
    when:
      event: tag

  publish:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

  trigger_dev_deploy:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/asl-deploy-bot
    branch: master
    secrets:
      - drone_token
    params: REPO=${DRONE_REPO},PLUGIN_NUMBER=${DRONE_BUILD_NUMBER}
    deploy_to: dev
    when:
      event: tag

  configure_deploy:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - mkdir deploy
      - npx kube-cookbook --out deploy .kube.$${DRONE_DEPLOY_TO}.yaml
    when:
      environment:
        - dev
        - preprod
      event: deployment

  dev_deploy:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    environment:
      KUBE_NAMESPACE: asl-dev
      INSECURE_SKIP_TLS_VERIFY: "TRUE"
    secrets:
      - kube_server
      - kube_token_dev
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_DEV}
      - kd -f deploy
    when:
      environment: dev
      event: deployment

matrix:
  NPM_AUTH_USERNAME:
    - asl
