pipeline:

  test:
    image: node:10
    secrets:
      - npm_auth_token
    environment:
      - POSTGRES_USER=asl-test
      - POSTGRES_HOST=database
      - DATABASE_NAME=asl-test
      - DATABASE_HOST=database
      - DATABASE_USERNAME=asl-test
    commands:
      - npm ci
      - npm test
    when:
      event: [push, pull_request, tag]

  audit:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npx @lennym/ciaudit
    when:
      event: [push, pull_request, tag]

  build:
    image: docker:17.09.1
    secrets:
      - npm_auth_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build --build-arg NPM_AUTH_USERNAME=$${NPM_AUTH_USERNAME} --build-arg NPM_AUTH_TOKEN=$${NPM_AUTH_TOKEN} -t asl-schema .
    when:
      event: [tag, pull_request]

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-schema quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
    when:
      event: tag

  publish:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

  update_manifest:
    image: quay.io/ukhomeofficedigital/asl-deploy-bot:latest
    secrets:
      - github_access_token
    commands:
      - update
        --repo ukhomeoffice/asl-deployments
        --token $${GITHUB_ACCESS_TOKEN}
        --file versions.yml
        --service asl-schema
        --version $${DRONE_TAG}
    when:
      event: tag

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=asl-test

matrix:
  NPM_AUTH_USERNAME:
    - asl
