pipeline:

  test:
    image: node:8
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request, tag]

  publish:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - echo "_authToken=$${NPM_AUTH_TOKEN}" >> .npmrc
      - npm publish
    when:
      event: tag
