pipeline:

  test:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm install
      - npm test
    when:
      event: [push, pull_request, tag]

  publish:
    image: node:8
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

matrix:
  NPM_AUTH_USERNAME:
    - asl
