pipeline:

  test:
    image: node:10
    secrets:
      - npm_auth_token
    environment:
      - POSTGRES_USER=asl-test
      - POSTGRES_HOST=database
      - DATABASE_NAME=asl-test
      - DATABASE_HOST=database
      - DATABASE_USERNAME=asl-test
    commands:
      - npm ci
      - npm test
    when:
      event: [push, pull_request, tag]

  audit:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npx @lennym/ciaudit
    when:
      event: [push, pull_request, tag]

  build:
    image: docker:17.09.1
    secrets:
      - npm_auth_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build --build-arg NPM_AUTH_USERNAME=$${NPM_AUTH_USERNAME} --build-arg NPM_AUTH_TOKEN=$${NPM_AUTH_TOKEN} -t asl-schema .
    when:
      event: [tag, pull_request]

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl-schema quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/asl-schema:$${DRONE_TAG}
    when:
      event: tag

  publish:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - npm publish
    when:
      event: tag

  trigger_dev_deploy:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/asl-deploy-bot
    branch: master
    secrets:
      - drone_token
    params: REPO=${DRONE_REPO},PLUGIN_NUMBER=${DRONE_BUILD_NUMBER}
    deploy_to: dev
    when:
      event: tag

  configure_deploy:
    image: node:10
    secrets:
      - npm_auth_token
    commands:
      - mkdir deploy
      - npx kube-cookbook --out deploy .kube.$${DRONE_DEPLOY_TO}.yaml
    when:
      environment:
        - dev
        - preprod
      event: deployment

  dev_deploy:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    environment:
      KUBE_NAMESPACE: asl-dev
      INSECURE_SKIP_TLS_VERIFY: "TRUE"
    secrets:
      - kube_server
      - kube_token_dev
    commands:
      - export KUBE_TOKEN=$${KUBE_TOKEN_DEV}
      - kd -f deploy
    when:
      environment: dev
      event: deployment

  dev_seed:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    secrets:
      - kube_server
      - kube_token_dev
    commands:
      - POD=$(kubectl --server=$${KUBE_SERVER} --namespace=asl-dev --token=$${KUBE_TOKEN_DEV} --insecure-skip-tls-verify=true get pods -o=jsonpath={.items[0].metadata.name} -l=name==database-admin)
      - kubectl --server=$${KUBE_SERVER} --namespace=asl-dev --token=$${KUBE_TOKEN_DEV} --insecure-skip-tls-verify=true exec $POD -- npm run seed
    when:
      environment: dev
      event: deployment

services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=asl-test

matrix:
  NPM_AUTH_USERNAME:
    - asl
